#!/bin/sh
echo "Launching Scala REPL..."
# Hack to give init.scala the command line arguments.
args="val args : Array[String] = Array("
i="0"
for a in $*;
do if [ "$i" -ne "0" ]; then 
   args="$args,"
   fi
   i="1"
  args="$args\"$a\""
done
args="$args)"
echo $args > _args.scala ;
cat init.scala - | scala  -cp \
.:$JLINK/JLink.jar:./commons-cli-1.2/commons-cli-1.2.jar \
`cat specialoptions` -Dscala.repl.power
# HACK. Need to do this or else mac terminal gets messed up.
reset
echo "Thank you for using KeYmaeraD."

