#!/bin/sh
scala -J-Xmx1000M -classpath .:./commons-cli-1.2/commons-cli-1.2.jar:$JLINK/JLink.jar KeYmaeraD.WorkerMain $* 
#java -Xmx1000M -classpath .:$SCALA_HOME/lib/scala-library.jar:./commons-cli-1.2/commons-cli-1.2.jar:$JLINK/JLink.jar KeYmaeraD/WorkerMain $* 