{}
C > 0,
C < 2,
H > 0,
G > 0
 |- [v:= 0; y:= H; 
     { {y' = v, v' = -G; y >= 0}
         @invariant(C > 0 & 
                    C < 1 &
	             H > 0 & 
		     G > 0,
                     v * v + 2 * G * y <= 2 * G * H)  ; 
         ((? y = 0; v := - C * v) ++ (? true))   }* 
	         @invariant(C > 0 &
			    C < 1 &
			    H > 0 &
			    G > 0 &
                            y >= 0 & 
			    v*v + 2 * G * y <= 2 * G * H )   ] y <= H

