v^2 <= 2*b*(m-z),
 b > 0,
 aa >=0,
 ep > 0
|- 
   [{
    SB := (v^2)* (1/ 2) + (aa + b)*((aa * (1/2))*ep^2 + ep*v);
    ((?((m - z) * b <=  SB); a:= -b) ++ (?(b * (m - z) >=  SB); a:=aa));
    t:=0; 
    {z'=v, v' = a, t'=1; v >= 0 & t <= ep}
      @solution(forall s . z(s) = z + v * s + a * s^2 * (1/ 2), 
                forall s . v(s) = v + a * s,
                forall s . t(s) = t + s)
    }*@invariant(v^2<=2*b*(m-z) & b > 0 & aa >= 0 & ep > 0)] 
z <= m
  

