dl('load, "examples/QdlSimpleDiff.dl")
val rl1 = allLeft(Fn("j", Nil));
val rl2 = allLeft(Fn("k", Nil));
dl('gotoroot)
dl('tactic, applyToLeavesT(trylistofrulesT(List(
  qDiffSolve(Endpoint)(List(
    parseFormula("forall t . x(t, i) = -(1/2) *b * t^2 + v(i) * t + x(i)"))) ))))
dl('tactic, applyToLeavesT(alleasyT))
dl('tactic, applyToLeavesT(trylistofrulesT(List(rl1))))
dl('tactic, applyToLeavesT(trylistofrulesT(List(rl2))))
dl('tactic, applyToLeavesT(trylistofrulesT(List(substitute))))
dl('tactic, applyToLeavesT(trylistofrulesT(List(substitute))))
dl('tactic, applyToLeavesT(trylistofrulesT(List(impLeft))))
dl('tactic, applyToLeavesT(trylistofrulesT(List(close))))
dl('tactic, applyToLeavesT(tryruleatT(hide)(LeftP(1) )))
dl('tactic, applyToLeavesT(tryruleatT(hide)(LeftP(3) )))
dl('tactic, applyToLeavesT(trylistofrulesT(List(rl1))))
dl('tactic, applyToLeavesT(trylistofrulesT(List(rl2))))
dl('tactic, applyToLeavesT(trylistofrulesT(List(substitute))))
dl('tactic, applyToLeavesT(trylistofrulesT(List(substitute))))
dl('tactic, applyToLeavesT(tryruleatT(hide)(LeftP(5) )))
dl('tactic, applyToLeavesT(tryruleatT(nullarize("x"))(LeftP(3))))
dl('tactic, applyToLeavesT(tryruleatT(nullarize("v"))(LeftP(3))))
dl('tactic, applyToLeavesT(nullarizeT))
dl('tactic, applyToLeavesT(arithT))
