dl('load, "examples/QdlSimpleDiff.dl")
dl('gotoroot)
dl('tactic, applyToLeavesT(trylistofrulesT(List(
  qDiffSolve(Endpoint)(List(
    parseFormula("forall t . x(t, i) = -(1/2) *b * t^2 + v(i) * t + x(i)"))) ))))
dl('tactic, applyToLeavesT(alleasyT))
dl('tactic, applyToLeavesT(instantiate0T))
dl('tactic, applyToLeavesT(repeatT(substT)))
dl('tactic, applyToLeavesT(trylistofrulesT(List(impLeft))))
dl('tactic, applyToLeavesT(trylistofrulesT(List(close))))
dl('tactic, applyToLeavesT(instantiate0T))
dl('tactic, applyToLeavesT(repeatT(substT)))
dl('tactic, applyToLeavesT(hideunivsT))
dl('tactic, applyToLeavesT(repeatT(nullarizeT)))
dl('tactic, applyToLeavesT(arithT))
